version: "3"

services:
  api:
    build: .
    container_name: api
    ports:
      - "9000:9000"
    tty: true
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd
      - MYSQL_DATABASE=kagong
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
